name = "og"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

[[rules]]
type = "Data"
globs = ["**/*.ttf"]
fallthrough = false

# Routes will be configured in Cloudflare dashboard
# og.iammatthias.com/* -> this worker
