/**
 * Azulejo PNG manifest. Auto-generated by `bun run snapshot:azulejos`
 * (see scripts/snapshot-azulejos.mjs in the parent repo).
 *
 * The script renders multiple seeded variations of the AzulejoTile via
 * headless Chromium, saves PNGs into ../azulejo/, and rewrites this
 * file with one import per PNG. The OG worker picks one deterministically
 * by URL hash so each card carries a permanent (but varied) accent.
 *
 * Empty list = no azulejo accent rendered (worker falls back to a
 * solid-color strip). Drop in PNGs and re-run the snapshot script to
 * populate.
 */

export const AZULEJOS: Uint8Array[] = [];
