/**
 * Azulejo PNG manifest. AUTO-GENERATED by scripts/snapshot-azulejos.mjs.
 * Do not edit by hand — re-run the script to refresh.
 *
 * Variations: 24
 */

import t01 from "../azulejo/01.jpg";
import t02 from "../azulejo/02.jpg";
import t03 from "../azulejo/03.jpg";
import t04 from "../azulejo/04.jpg";
import t05 from "../azulejo/05.jpg";
import t06 from "../azulejo/06.jpg";
import t07 from "../azulejo/07.jpg";
import t08 from "../azulejo/08.jpg";
import t09 from "../azulejo/09.jpg";
import t10 from "../azulejo/10.jpg";
import t11 from "../azulejo/11.jpg";
import t12 from "../azulejo/12.jpg";
import t13 from "../azulejo/13.jpg";
import t14 from "../azulejo/14.jpg";
import t15 from "../azulejo/15.jpg";
import t16 from "../azulejo/16.jpg";
import t17 from "../azulejo/17.jpg";
import t18 from "../azulejo/18.jpg";
import t19 from "../azulejo/19.jpg";
import t20 from "../azulejo/20.jpg";
import t21 from "../azulejo/21.jpg";
import t22 from "../azulejo/22.jpg";
import t23 from "../azulejo/23.jpg";
import t24 from "../azulejo/24.jpg";

export const AZULEJOS: Uint8Array[] = [t01, t02, t03, t04, t05, t06, t07, t08, t09, t10, t11, t12, t13, t14, t15, t16, t17, t18, t19, t20, t21, t22, t23, t24];
